name: deployment to production server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: update anon chat bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/telegram-anon-chat
            git pull origin master
            rm -rf .env
            cat << WRITEDATA >> .env
            BOT_TOKEN = "${{ secrets.ENV_BOT_TOKEN }}"
            DB_URL = "${{ secrets.ENV_DB_URL }}"
            OWNER_CHAT_ID = ${{ secrets.ENV_OWNER_CHAT_ID }}
            docker-compose up -d --build
